### ISSUE TITLE
Dokumentasjon - CSS

### ISSUE THREAD

**Issue by lha047** [Mattilsynet/designsystem#853]

**Comment by lha047** [comment]
For accessibility all animation and transitions should be in the media query `prefers-reduced-motion: no-preference`
```css
@media (prefers-reduced-motion: no-preference) {
  html {
    scroll-behavior: smooth;
  }
}
```
